# Generated by Django 3.2 on 2021-04-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210412_1937'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow-author-constraint',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='follow',
            new_name='following',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='user-following-constraint'),
        ),
    ]
